import { jsPDF } from "jspdf";
import type { DisplayLabel } from "@/types";

interface ReportData {
  patientId: string;
  scanDate: string;
  label: DisplayLabel;
  confidence: number;
  previewUrl: string | null;
  heatmap: string | null;
}

export async function generateReportPdf(data: ReportData): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();

  doc.setFillColor(5, 11, 26);
  doc.rect(0, 0, pageW, 40, "F");
  doc.setTextColor(76, 201, 240);
  doc.setFontSize(22);
  doc.text("NEURO-XAI", pageW / 2, 18, { align: "center" });
  doc.setFontSize(10);
  doc.setTextColor(200, 220, 255);
  doc.text("Precision Diagnostics. Explainable Intelligence.", pageW / 2, 26, { align: "center" });
  doc.text("DIAGNOSTIC REPORT", pageW / 2, 34, { align: "center" });

  doc.setTextColor(10, 15, 30);
  doc.setFontSize(11);
  let y = 50;
  doc.text(`Patient ID: ${data.patientId}`, 20, y);
  y += 8;
  doc.text(`Scan Date: ${data.scanDate}`, 20, y);
  y += 12;
  doc.setFontSize(14);
  doc.setTextColor(255, 77, 109);
  doc.text(`Classification: ${data.label}`, 20, y);
  y += 8;
  doc.setFontSize(11);
  doc.setTextColor(10, 15, 30);
  doc.text(`Confidence: ${(data.confidence * 100).toFixed(1)}%`, 20, y);
  y += 8;
  doc.text("Severity: HIGH", 20, y);
  y += 12;

  doc.setFontSize(10);
  const notes =
    "Cross-Gated Multi-Path Attention Fusion detected high-density activations in periventricular regions. Grad-CAM, SHAP, and LIME analyses support this finding. Recommend neuroradiology follow-up within 72 hours.";
  const split = doc.splitTextToSize(notes, pageW - 40);
  doc.text(split, 20, y);

  doc.setDrawColor(76, 201, 240);
  doc.line(20, 270, pageW - 20, 270);
  doc.setFontSize(8);
  doc.setTextColor(100, 120, 150);
  doc.text("Generated by Neuro-XAI Clinical Platform | Confidential", pageW / 2, 278, { align: "center" });

  doc.save(`Neuro-XAI-Report-${data.patientId}.pdf`);
}
